### ISSUE TITLE
Feature Request: Clickable Citations

### ISSUE THREAD

**Issue by expnn** [jacob-pro/mdbook-bibfile-referencing#2]
The `pandoc` has a feature to generate clickable citations. It is a valuable feature to generate web pages with clickable citations. I had tried to add a line: 

```rust
p.add_option(PandocOption::Meta("link-citations".into(), Some("true".into())));
```

after this line https://github.com/jacob-pro/mdbook-bibfile-referencing/blob/71b06fecaa4141362c2339ffa78c3ed7bcc5fa7f/src/main.rs#L101, to enable the clickable citation, which, for sure did generated citations with `<a href="#ref-id" >...</a> ` tags, but the `ref-id`s are missing from the generated bibliography. This result in a failure to jump to the reference item when clicked. It seems this preprocessor is ignored some information generated by `pandoc`.

**Comment by jacob-pro** [comment]
Hi - I didn't know that pandoc supported this - but it is a feature I would really like to have too.
I will try and investigate this when I have time

**Comment by jacob-pro** [comment]
Ok I have now added support for enabling this, by setting an argument  `--link-citations`

With the links, it seems to be that not all the pandoc markdown flavours support adding the anchors, but it for me it seems to work with the commonmark and markdown_phpextra flavours. I have added the `--flavour` flag so you can set this:

```
[preprocessor.bibliography]
command = "cargo run src/bibliography.bib src/ieee.csl --flavour commonmark --link-citations"
```

I think in a future version I might make `commonmark` the default, and enable citation links by default - but would like to know if this works for you first?

**Comment by expnn** [comment]
Yes, it works! Thank you very much! 

There is a typo in your comment. The command should be 
```toml
command = "mdbook-bibfile-referencing src/bibliography.bib src/ieee.csl --flavour commonmark --link-citations"
```
instead of the ``cargo run`` command.

**Comment by jacob-pro** [comment]
👍 Ah yep - that is the command I use for testing within the project directory 😆

**Comment by jacob-pro** [comment]
Hi,

I have now updated it so that links are now enabled by default / no arguments are required

There is also a test case to verify it is working https://github.com/jacob-pro/mdbook-bibfile-referencing/blob/b8effd816826b6cddc4a2fa5a25f3afea3fd47d7/src/test.rs#L5

https://github.com/jacob-pro/mdbook-bibfile-referencing/blob/b8effd816826b6cddc4a2fa5a25f3afea3fd47d7/src/test.rs#L11

Please try out [version 0.3.0](https://crates.io/crates/mdbook-bibfile-referencing/0.3.0)
