### ISSUE TITLE
Deal with Latex and syntax highlighting

### ISSUE THREAD

**Issue by abel0b** [jacob-pro/mdbook-bibfile-referencing#3]
This preprocessor breaks syntax highlighting and Latex equations (via mathjax).

When mdbook-bibfile-referencing is disabled:
![before](https://user-images.githubusercontent.com/5240014/203783582-ce831081-e15b-4732-a8f6-ec93592ea728.png)

When it is enabled :
![after](https://user-images.githubusercontent.com/5240014/203783594-479e5f53-f687-4821-8022-cd918aba8d8a.png)

The code I used:
```markdown
# Chapter 1

\\[\mu = \frac{1}{N} \sum_{i=0} x_i\\]

```C
#include <stdio.h>

int main() {
    printf("Hello world!\n");
    return 0;
}
```

**Comment by jacob-pro** [comment]
Hi,

I think the issue you're having isn't really a fault of this project - but pandoc itself?

I think what is happening is that pandoc is interpreting the square brackets as a quotation

https://pandoc.org/demo/example19/Extension-citations.html

Essentially all this program does is wrap the command:

```bash
pandoc -f markdown_strict --csl ieee.csl --citeproc --bibliography bibliography.bib input.txt
```

Maybe using a different flavour of markdown might fix it - if so I could make that change.

Please can you check and see if the same thing happens with that command? And if so maybe you can open an issue at https://github.com/jgm/pandoc/issues instead?

**Comment by abel0b** [comment]
Yes. For syntax highlighting, using Github Flavored Markdown (-f gfm) seems to work.
Not sure how to support latex with Pandoc yet.

Maybe mdbook-bibfile-referencing should have and option to configure the markdown flavor ?

**Comment by jacob-pro** [comment]
I have now added the `--flavour` command so you should be able to use:

```
[preprocessor.bibliography]
command = "cargo run src/bibliography.bib src/ieee.csl --flavour markdown-github"
```

Please can you let me know if this fixes the issue?

**Comment by jacob-pro** [comment]
I've managed to get the mathjax working as per your sample above

![image](https://user-images.githubusercontent.com/16433349/206917775-f2b11cf0-a5fc-4457-a57e-9f12a1155c06.png)

To get it to work I had to change the input format from `markdown_strict` to `markdown_github` - this is now the default so it should work automaticaly

Please try out [version 0.3.0](https://crates.io/crates/mdbook-bibfile-referencing/0.3.0)
